### ISSUE TITLE
Build gets stuck after success

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuepress#580]
#### Version

Tested with 9.1 and 10.1

#### Steps to reproduce

```
vuepress build
```

This happens ONLY in this repository: `git@gitlab.com:MartinMuzatko/wire-up-your-front-ends.git` or download from here: https://gitlab.com/MartinMuzatko/wire-up-your-front-ends

My other vuepress project builds fine, but since this project is based off of previous projects I don't see any problem..

#### What is expected?

command finishes

#### What is actually happening?

command never finishes and is stuck at "Success! Generated static files "

I never get returned to the CLI prompt
![image](https://user-images.githubusercontent.com/2950505/41353619-08f5b8e6-6f1d-11e8-9918-b81725084d6b.png)

This wouldn't be that drastic, if CI systems don't need the command to finish in order to publish.

#### Other relevant information

- Your OS: Windows 10 (but the build also gets stuck on netlify)
- Node.js version: 8.9.x
- Is this a global or local install? both, tried via package.json and global
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Oh, reproduced!

**Comment by ulivz** [comment]
@MartinMuzatko 

In fact, I think we should avoid introducing `process.exit` in code, but this is the second time someone has encountered this problem, so I just solved it like this. I also think that this should be a problem with userland's code.

If you can find the root cause, please tell me, thank you!

**Comment by MartinMuzatko** [comment]
When removing `setInterval` within `created` method, the build ends fine without `process.exit`. To me it looks like Vue SSR tries to wait for anything that it could prepare. But then the build process should get stuck somewhere else.

**Comment by MartinMuzatko** [comment]
I also fixed it by moving the `setInterval` to the `mounted` function :) so yes - my assumption should be correct

**Comment by ulivz** [comment]
Thanks, I just reverted the fix.

**Comment by MartinMuzatko** [comment]
@ulivz is this something that Vue SSR should deal with? Or is this just common practice that timeouts/intervals should be avoided in `created`?

**Comment by jwerak** [comment]
Hi, I can still see the issue on `vuepress/1.0.0-alpha.36 linux-x64 node-v8.15.0`. 
Is there any resolution to this?
